import type { Metadata } from "next";
import "./globals.css";
import Navi from "./components/Navi/Navi";

export const metadata: Metadata = {
  title: "SHIO PROJECT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="min-h-screen bg-gray-50 text-gray-900 antialiased">
        <div className="flex h-full flex-col">
          <Navi />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
